### ISSUE TITLE
"Derived from" relationships between period definitions

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-data#15]
Need to decide how to represent relationships between period definitions e.g. "derived from".

**Comment by ptgolden** [comment]
Adam says:

> "Derived from" in #15 is different from sub-periods (= "broader" in the spreadsheet). Derived from means a new period is a modification of an existing period (like, I'm using Shelmerdine's definition of LMIIIB, but I want to push the end-date down 50 years). A sub-period is like splitting Iron Age into Iron Age I, Iron Age II, etc. The first is genetic, the second hierarchical.

**Comment by atomrab** [comment]
I had a conversation with Lisa this morning, and being able to express "derived from" is going to be particularly important (I will follow up on this by email).

**Comment by rybesh** [comment]
We will use [prov:wasDerivedFrom](https://www.w3.org/TR/prov-o/#wasDerivedFrom) for derivation relations.

**Comment by rybesh** [comment]
@atomrab what is the convention you have been following to record notes about derivations? I'd like to experiment with programmatically adding these to the dataset.

**Comment by atomrab** [comment]
We've simply written "Derived from" + valid PeriodO URI in the "Editorial Notes" field, which should be easy enough to extract. See e.g. http://n2t.net/ark:/99152/p0qhb66942z.

**Comment by rybesh** [comment]
Proposed changes to the data model [1] and script to generate patch are ready, just waiting on new client to deploy to submit patch.

[1]https://github.com/periodo/periodo-validation/blob/derived-from/changes/proposed/derived-from/constraints-added.ttl

**Comment by rybesh** [comment]
Fixed by https://github.com/periodo/periodo-server/pull/71

These changes have been deployed to https://staging.perio.do but not yet to the canonical server. However I am going to go ahead and close the bug.
