### ISSUE TITLE
CSV mapping

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-data#17]
To map to a CSV output, we need to decide how to handle
  * Spatial coverage (I'm fine with just including the description)
  * Alternate labels
  * Localized labels

**Comment by atomrab** [comment]
I would vote for a URI (or series of URIs) for spatial coverage along with the description (for people who want to do mapping). I think it's enough to have the localized label (what's the question about this? What to call the column?). Alternate labels are rare, and a user can extract them from the original label if desired.

**Comment by rybesh** [comment]
1. `spatialCoverage`: pipe-separated list of URIs
2. `alternateLabel`: pipe-separated list of strings
3. `localizedLabel`: redundant, do not include

**Comment by ptgolden** [comment]
This is more of an issue with the client, since I don't think we plan on maintaining an updated repository of CSV dumps of every period collection.

It's been implemented in the client for a while, it lives at https://github.com/periodo/periodo-client/blob/v0.6.8/src/helpers/periodization.js#L37-L84
