### ISSUE TITLE
Provenance issues

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-data#25]
In the provenance graph we currently have, there are statements like this one:

```json
"specializationOf": "http://n2t.net/ark:/99152/p086kj9kr9q",
"wasRevisionOf": 
{
    "id": "http://n2t.net/ark:/99152/p086kj9kr9q?version=0"
}
```

Couple questions:
  1. Does wasRevisionOf need to be a JSON object? Can it be a simple string, with the mapping to id done in the JSON-LD context?
  2. Should we have wasRevisionOf values for new assertions/collections? wasRevisionOf only makes sense to me when the new version was actually a revision of something that already existed.

Also, we're not currently including `type` information (i.e. prov:Activity and prov:Entity). Was the on purpose? Are those implied by the relationships between things?

**Comment by rybesh** [comment]
> Does wasRevisionOf need to be a JSON object? 

No.

> Can it be a simple string, with the mapping to id done in the JSON-LD context?

Yes. 

> Should we have wasRevisionOf values for new assertions/collections? 

No.

All the above issues were addressed by https://github.com/periodo/periodo-server/pull/36.

> we're not currently including type information (i.e. prov:Activity and prov:Entity). Was the on purpose?

Yes.

> Are those implied by the relationships between things?

Yes.
