### ISSUE TITLE
Content needing correction (for Adam; Ryan and Patrick ignore)

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-data#27]
I'm just going to use the issue tracker to keep track of input errors that I need to go back and fix later. This one is for http://n2t.net/ark:/99152/p0wf3wdnm6q, which should be checked but appears to need an alternate name and end in 238 BC, not 476 AD. We could fix some of the alternate labels here, too -- some didn't make it out of the editorial notes.

**Comment by rybesh** [comment]
@atomrab Did this get fixed?

**Comment by atomrab** [comment]
Not yet, workin' on it.

**Comment by atomrab** [comment]
Fix LCSH spatial coverage for the following:

http://n2t.net/ark:/99152/p06c6g3q4rw (should be Charleston (S.C.)
http://n2t.net/ark:/99152/p06c6g3w8n6 (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3gwfd (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g39znk (add spatial coverage to this and other refs to Upper Silesia)
http://n2t.net/ark:/99152/p06c6g3rsfd (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3mk6v (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3kxpd (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g36frw (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3bn87 (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g35p2k (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3gbbc (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3bgn6 (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3mvcf (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g35bqm (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3gbbc (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g38hqk (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3zq65 (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g35frp (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3qn63 (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g34wxb (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3ztjv (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3wr9t (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3wmvj (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3mx7r (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3t73q (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3gvtd (edit description, add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3nj6t (edit description, add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3v2tv (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3x457 (add spatial coverage, remove additional label)
http://n2t.net/ark:/99152/p06c6g3fjfk (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g38gp2 (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3pmfn (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3hswp (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g38v5f (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3qwcc (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3v9qs (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g37ts9 (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3z962 (add additional spatial coverage)
http://n2t.net/ark:/99152/p06c6g32xhk (edit description)
http://n2t.net/ark:/99152/p06c6g3mrpb (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3g99s (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3rpqz (add spatial coverage)
http://n2t.net/ark:/99152/p06c6g3rcqn (change from Florida to Iowa)

**Comment by atomrab** [comment]
Fix LCSH label issues and typos for the following:

Fix Heraclius (typo in date)
Remove the Byzantine Empire spatial coverage (check with Ryan)
Add alt label to http://id.loc.gov/authorities/subjects/sh85108068.html
Add alternate labels to http://id.loc.gov/authorities/subjects/sh85131068.html and http://id.loc.gov/authorities/subjects/sh85048376.html
Fix spacing at http://n2t.net/ark:/99152/p06c6g3hk5w and http://n2t.net/ark:/99152/p06c6g3dwcc, add alt labels to latter from http://id.loc.gov/authorities/subjects/sh85024078.html 
Edit antislavery movement, http://id.loc.gov/authorities/subjects/sh85015933.html
Update end dates for alternate labels for Syria conflict at http://n2t.net/ark:/99152/p06c6g3kxqp
For French and Indian War (http://id.loc.gov/search/?q=french+and+indian+war+1755&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects), add Quebec (and cities?); add alt labels with 1755 as start date, convert all start dates to 2-part (1754, 1755)
Add alt label "French Revolution, 1789-1799" to http://n2t.net/ark:/99152/p06c6g38xfb, according to http://id.loc.gov/authorities/subjects/sh85051319.html
Add alt label to http://n2t.net/ark:/99152/p06c6g365zm
Add alt labels to http://n2t.net/ark:/99152/p06c6g3mgb9
Add alt label and update date range for http://n2t.net/ark:/99152/p06c6g3nzt9
Add alt labels to http://n2t.net/ark:/99152/p06c6g3g7qt
Add alt label to http://n2t.net/ark:/99152/p06c6g3fwnx
Add alt labels to http://n2t.net/ark:/99152/p06c6g3fv9q
Check accentuation of http://n2t.net/ark:/99152/p06c6g37h32
Add alt label to http://n2t.net/ark:/99152/p06c6g3gwtn, http://n2t.net/ark:/99152/p06c6g37hvj, http://n2t.net/ark:/99152/p06c6g3p9cq, http://n2t.net/ark:/99152/p06c6g3mb63
Add alt label to http://n2t.net/ark:/99152/p06c6g35xsm
Add alt labels to http://n2t.net/ark:/99152/p06c6g3dnzk
Add alt label to http://n2t.net/ark:/99152/p06c6g3hndh, http://n2t.net/ark:/99152/p06c6g3cbpn
Check accentuation of http://n2t.net/ark:/99152/p06c6g3b8ft
Add alt labels to http://n2t.net/ark:/99152/p06c6g3frgf, http://n2t.net/ark:/99152/p06c6g3mddc, http://n2t.net/ark:/99152/p06c6g32xvj
Add alt label to http://n2t.net/ark:/99152/p06c6g3tjwv
Add alt labels to http://n2t.net/ark:/99152/p06c6g365zm
Add alt label to http://n2t.net/ark:/99152/p06c6g33qq2
Add alt labels to http://n2t.net/ark:/99152/p06c6g3q6xw
Add alt label to http://n2t.net/ark:/99152/p06c6g3nhkt
Add alt label and adjust spatial coverage dx for http://n2t.net/ark:/99152/p06c6g3k9m5
Remove alt label from http://n2t.net/ark:/99152/p06c6g36v4p

**Comment by rybesh** [comment]
Except for the one in the initial comment on Jul 26, 2015, which I've moved to #76, the rest of these appear to have been fixed. @atomrab please re-open if I'm wrong about that.
