### ISSUE TITLE
Reduplication of labels in JSON

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-data#29]
Lex caught this in the local collection Sarah made for the CHGIS periods. Some but not all of these periods have double alternate labels in the JSON (these do not appear in the client view). What is going on here, and how do we get rid of them if they're not visible for deletion? Should I have Sarah start over?

[periodo-guide2-1449883467897.zip](https://github.com/periodo/periodo-data/files/69011/periodo-guide2-1449883467897.zip)

**Comment by rybesh** [comment]
That's an odd one. Any idea what is going on @ptgolden?

**Comment by rybesh** [comment]
Oh, and yes I verified that I'm seeing the same thing.

**Comment by rybesh** [comment]
@atomrab Did this get fixed? I'm assuming so, since it hasn't been mentioned in over a year…

**Comment by atomrab** [comment]
Whatever it was, we got rid of it somehow in the CHGIS patch submitted to the canonical database, and I haven't seen this issue occur again, so I'm going to conclude that we can close the issue.
