### ISSUE TITLE
Broader/narrower relations between period definitions

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-data#32]
E.g. splitting Iron Age into Iron Age I, Iron Age II, etc. The first should have `skos:narrower` relations to the rest, and the rest should have `skos:broader` relations to the first.

**Comment by atomrab** [comment]
Most of this will be obvious, I imagine, from the combination of date-range and location in specific collections, but in some where it was part of the data we received, we also noted this by label in the Editorial Notes field for the *subperiods only*: see eg http://n2t.net/ark:/99152/p0fp7wv5c3f. If you have a specific way you'd like me to structure this for the geological periods, let me know -- those have formal relationships between period, epoch, era, etc. in the Paleobiology Database.

**Comment by rybesh** [comment]
Fixed by https://github.com/periodo/periodo-server/pull/69

These changes have been deployed to https://staging.perio.do but not yet to the canonical server. However I am going to go ahead and close the bug.
