### ISSUE TITLE
19 periods missing structured descriptions of temporal coverage

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-data#35]
These period definitions have labels for their start and stop intervals, but are missing structured representations of one or the other. Was this an oversight, or done intentionally?

http://n2t.net/ark:/99152/p03tqbzrjp5
http://n2t.net/ark:/99152/p03tqbzvh6x
http://n2t.net/ark:/99152/p077fc5wvfd
http://n2t.net/ark:/99152/p083p5r6mhk
http://n2t.net/ark:/99152/p086kj96g7t
http://n2t.net/ark:/99152/p08m57h5rns
http://n2t.net/ark:/99152/p08m57hj8t4
http://n2t.net/ark:/99152/p08m57hmj8v
http://n2t.net/ark:/99152/p08m57htf9q
http://n2t.net/ark:/99152/p0bd664gkrp
http://n2t.net/ark:/99152/p0pqptcjxw3
http://n2t.net/ark:/99152/p0pqptcqkgd
http://n2t.net/ark:/99152/p0zj6g88v93
http://n2t.net/ark:/99152/p0zj6g8dzzb
http://n2t.net/ark:/99152/p0zj6g8hpfq
http://n2t.net/ark:/99152/p0zj6g8ktnf
http://n2t.net/ark:/99152/p0zj6g8p57k
http://n2t.net/ark:/99152/p0zj6g8tddc
http://n2t.net/ark:/99152/p0zj6g8ztv9

**Comment by atomrab** [comment]
Guessing oversight -- will go through and check.

**Comment by atomrab** [comment]
Most of these are just oversight, and I can fix. But the periods from the Arena ADS collection are a little more complicated. They were based on graphic timelines than ran up to "the present" and faded out, so there was no clear expression of an endpoint. A few also didn't have clear beginning points. How should we handle this? Can we have four-part dates with an indeterminate earliest or latest figure -- e.g. the modern period has earliest stop 2004 (when the ADS interface was posted), latest stop blank?

This is fixable more easily for the uncertain beginnings -- I can go back and look at my screen-grabs (the site doesn't exist any longer) and set earliest/latest starts. But in general, how do we handle the moving goalpost of "the present"?

**Comment by rybesh** [comment]
> They were based on graphic timelines than ran up to "the present" and faded out, so there was no clear expression of an endpoint … in general, how do we handle the moving goalpost of "the present"?

Good question; I'm surprised this hasn't come up before. I think the proper way to handle these would be to record them as temporal ranges that have a start interval but no stop interval. So a timeline that visually indicates "continues indefinitely into the future," or a sentence like "The Anthropocene began on July 16, 1982 and has not yet ended" would both be represented having no stop interval.

The client probably expects definitions to have stop intervals, though, so if we were to allow this we'd need to investigate the consequences in terms of breaking the client.

I don't think there's a use for temporal ranges with no start interval, is there?

**Comment by ptgolden** [comment]
Related to https://github.com/periodo/periodo-client/issues/150

**Comment by rybesh** [comment]
These have been fixed, and we now allow periods without stop intervals.
