### ISSUE TITLE
Question: what to do with identical LoC entries associated with different spatial coverage?

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-data#36]
For the most part, the LoC period subject headings refer to one and only one country/spatial entity. In the case of periods for the Austro-Hungarian Empire, the LoC has two sets: one for Austria, the other for Hungary. But the periods themselves are otherwise identical. Elsewhere, we have simply added two countries to the coverage. But these periods have separate URIs in the online LoC. Do we simply produce two separate entries, one for Austria and one for Hungary, following the LoC exactly? Or do we make a single entry that maps to two nations and two URIs? 

I assume the former, but I just wanted to check.

**Comment by rybesh** [comment]
I agree that we should do the former: two separate period definitions.
