### ISSUE TITLE
Invalid gYear values

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-data#37]
We have 48 instances of invalid `gYear` values in the canonical dataset. These values are things like `400` (should be `0400`), `-271` (should be `-0271`), and `0000` (there is no ISO year zero). Probably easiest to fix these as a batch programmatically, but before that we need to prevent it from happening in the first place (see https://github.com/periodo/periodo-client/issues/118).

**Comment by atomrab** [comment]
I did understand ISO8601 to have a year zero in the form 0000, which is
equivalent to the Gregorian 1 BC. If there isn't, why do we parse 2 BC as
-0001?

**Comment by rybesh** [comment]
Sorry, you're right. The reason I've been posting all these data bugs is because I've been working with some new validation tools, that can check some of the assumptions we make about how the data can be structured. Anyway, these tools were telling me that `0000` is an invalid `gYear` value, and checking the [XML Schema Datatypes spec](https://www.w3.org/TR/xmlschema-2/#noYearZero) confirmed this… except I always forget that there is a difficult-to-Google [XML Schema Definition Language Datatypes spec](https://www.w3.org/TR/xmlschema11-2/#dateTime-value-space) which is more recent and which is the one we follow. Unfortunately these tools follow the obsolete-but-far-more-prominent spec. I will file a bug with them. In the meantime this bug still stands for the non-zero-padded `gYear` values.

**Comment by rybesh** [comment]
Bug filed at https://github.com/TopQuadrant/shacl/issues/10

**Comment by rybesh** [comment]
Created a patch that fixes the zero-padding issue for `gYear` values < 1000: https://test.perio.do/#/patches/https://test.perio.do/patches/54/

We can close this issue when @atomrab accepts the patch.

Note that this just fixes the data; we still need to prevent this from happening again by fixing https://github.com/periodo/periodo-client/issues/118

**Comment by atomrab** [comment]
I've got a problem with this patch -- I submitted, but it stripped the ISO dates from affected entries with date ranges altogether. See http://n2t.net/ark:/99152/p02q72z6c67. Do I have to find all the affected entries and re-enter the ranges manually? I think I have JSON files from which I can reconstruct them, but it will be kind of a pain.

**Comment by rybesh** [comment]
Crap, sorry about that, it was a problem in the patch. You already accepted it, right? I will create a new patch to fix the problems I introduced.

**Comment by atomrab** [comment]
Yeah, I did accept it -- I couldn't tell from the review page what the
actual changes were (there were strike-outs for these, and I should have
been suspicious, but the rest of the records showed neither additions nor
deletions, so I wasn't sure).

**Comment by rybesh** [comment]
OK, this patch should fix the problems that the last patch introduced:
https://test.perio.do/#/patches/https://test.perio.do/patches/55/

**Comment by rybesh** [comment]
OK, I went ahead and merged patch 55.
