### ISSUE TITLE
ell-latn language tag

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-data#38]
A number of the Ariadne definitions have the language tag `ell-latn` on their preferred labels, but these labels are in Greek script, not Latin. @atomrab, can you verify that these are errors? Full list below.

http://n2t.net/ark:/99152/p0qhb6628nh
http://n2t.net/ark:/99152/p0qhb662trj
http://n2t.net/ark:/99152/p0qhb662z9q
http://n2t.net/ark:/99152/p0qhb6633fn
http://n2t.net/ark:/99152/p0qhb6642m4
http://n2t.net/ark:/99152/p0qhb6643mc
http://n2t.net/ark:/99152/p0qhb66472n
http://n2t.net/ark:/99152/p0qhb664f27
http://n2t.net/ark:/99152/p0qhb664td2
http://n2t.net/ark:/99152/p0qhb665dff
http://n2t.net/ark:/99152/p0qhb665vpv
http://n2t.net/ark:/99152/p0qhb6668db
http://n2t.net/ark:/99152/p0qhb666rpb
http://n2t.net/ark:/99152/p0qhb666zg4
http://n2t.net/ark:/99152/p0qhb667873
http://n2t.net/ark:/99152/p0qhb667vht
http://n2t.net/ark:/99152/p0qhb6695gs
http://n2t.net/ark:/99152/p0qhb669r6t
http://n2t.net/ark:/99152/p0qhb66b989
http://n2t.net/ark:/99152/p0qhb66fv6h
http://n2t.net/ark:/99152/p0qhb66g38m
http://n2t.net/ark:/99152/p0qhb66hcfd
http://n2t.net/ark:/99152/p0qhb66hxr7
http://n2t.net/ark:/99152/p0qhb66jcv6
http://n2t.net/ark:/99152/p0qhb66jh4z
http://n2t.net/ark:/99152/p0qhb66jpqb
http://n2t.net/ark:/99152/p0qhb66jr4s
http://n2t.net/ark:/99152/p0qhb66k3z7
http://n2t.net/ark:/99152/p0qhb66k7q6
http://n2t.net/ark:/99152/p0qhb66kwv9
http://n2t.net/ark:/99152/p0qhb66mj5z
http://n2t.net/ark:/99152/p0qhb66p2j3
http://n2t.net/ark:/99152/p0qhb66p53z
http://n2t.net/ark:/99152/p0qhb66ps4x
http://n2t.net/ark:/99152/p0qhb66ps4x
http://n2t.net/ark:/99152/p0qhb66q6ff
http://n2t.net/ark:/99152/p0qhb66s4gn
http://n2t.net/ark:/99152/p0qhb66s75r
http://n2t.net/ark:/99152/p0qhb66sctf
http://n2t.net/ark:/99152/p0qhb66sm2q
http://n2t.net/ark:/99152/p0qhb66sspc
http://n2t.net/ark:/99152/p0qhb66szh6
http://n2t.net/ark:/99152/p0qhb66tdgx
http://n2t.net/ark:/99152/p0qhb66v39c
http://n2t.net/ark:/99152/p0qhb66v534
http://n2t.net/ark:/99152/p0qhb66vjx3
http://n2t.net/ark:/99152/p0qhb66vqkd
http://n2t.net/ark:/99152/p0qhb66wcdj
http://n2t.net/ark:/99152/p0qhb66wrq3
http://n2t.net/ark:/99152/p0qhb66x582
http://n2t.net/ark:/99152/p0qhb66x8n3
http://n2t.net/ark:/99152/p0qhb66xcnt
http://n2t.net/ark:/99152/p0qhb66xjj8
http://n2t.net/ark:/99152/p0qhb66z499

**Comment by atomrab** [comment]
Confirmed -- these should be ell-grek, if we're using ISO 15924 for script. Confirm, and I'll go through and fix these manually.

**Comment by rybesh** [comment]
No need to fix them manually, I will generate a patch as part of my fix for https://github.com/periodo/periodo-data/issues/30
