### ISSUE TITLE
als-latn language tag

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-data#39]
A number of the Ariadne and FASTI definitions have the language tag `als-latn` on their preferred labels. `als` is the language code for [Tosk Albanian](https://en.wikipedia.org/wiki/Tosk_Albanian), “the southern dialect group of the Albanian language, spoken by the ethnographic group known as Tosks.” @atomrab, can you verify that this is indeed the correct language tag, and not (as I suspect) `sq`, which the language code for [Albanian in general](https://en.wikipedia.org/wiki/Albanian_language)? Full list of affected definitions is below.

http://n2t.net/ark:/99152/p06v8w47jcw
http://n2t.net/ark:/99152/p06v8w48qxz
http://n2t.net/ark:/99152/p06v8w496hs
http://n2t.net/ark:/99152/p06v8w49hzs
http://n2t.net/ark:/99152/p06v8w49mp2
http://n2t.net/ark:/99152/p06v8w4bjgp
http://n2t.net/ark:/99152/p06v8w4bnsk
http://n2t.net/ark:/99152/p06v8w4br75
http://n2t.net/ark:/99152/p06v8w4d6vw
http://n2t.net/ark:/99152/p06v8w4hx4w
http://n2t.net/ark:/99152/p06v8w4jhjm
http://n2t.net/ark:/99152/p06v8w4kbt3
http://n2t.net/ark:/99152/p06v8w4m9zc
http://n2t.net/ark:/99152/p06v8w4mkjq
http://n2t.net/ark:/99152/p06v8w4nfqg
http://n2t.net/ark:/99152/p06v8w4rbc2
http://n2t.net/ark:/99152/p06v8w4s3k7
http://n2t.net/ark:/99152/p06v8w4sm9z
http://n2t.net/ark:/99152/p06v8w4vck4
http://n2t.net/ark:/99152/p06v8w4wpdc
http://n2t.net/ark:/99152/p06v8w4x58t
http://n2t.net/ark:/99152/p06v8w4xtf5
http://n2t.net/ark:/99152/p06v8w4xz8n
http://n2t.net/ark:/99152/p0qhb6623vz
http://n2t.net/ark:/99152/p0qhb662487
http://n2t.net/ark:/99152/p0qhb6626cm
http://n2t.net/ark:/99152/p0qhb662s6j
http://n2t.net/ark:/99152/p0qhb66357d
http://n2t.net/ark:/99152/p0qhb663rsj
http://n2t.net/ark:/99152/p0qhb664h77
http://n2t.net/ark:/99152/p0qhb6658kk
http://n2t.net/ark:/99152/p0qhb6674pv
http://n2t.net/ark:/99152/p0qhb667ddk
http://n2t.net/ark:/99152/p0qhb6687t3
http://n2t.net/ark:/99152/p0qhb6699r7
http://n2t.net/ark:/99152/p0qhb66ckx7
http://n2t.net/ark:/99152/p0qhb66d2kk
http://n2t.net/ark:/99152/p0qhb66dx47
http://n2t.net/ark:/99152/p0qhb66hmw3
http://n2t.net/ark:/99152/p0qhb66ht2h
http://n2t.net/ark:/99152/p0qhb66jzqd
http://n2t.net/ark:/99152/p0qhb66mvv8
http://n2t.net/ark:/99152/p0qhb66n9sq
http://n2t.net/ark:/99152/p0qhb66r4x9
http://n2t.net/ark:/99152/p0qhb66s5m4
http://n2t.net/ark:/99152/p0qhb66sp82
http://n2t.net/ark:/99152/p0qhb66tcgp
http://n2t.net/ark:/99152/p0qhb66tkjt
http://n2t.net/ark:/99152/p0qhb66vfdt
http://n2t.net/ark:/99152/p0qhb66whc9
http://n2t.net/ark:/99152/p0qhb66x9v4

**Comment by atomrab** [comment]
The Albanians confirm that sq is the correct language tag. Can we carry out a bulk change?

**Comment by rybesh** [comment]
Yes we can.
