### ISSUE TITLE
yearPublished is sometimes not a year

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-data#46]
Currently we define `yearPublished` in our JSON-LD context as follows:

```jsonld
    "yearPublished": {
      "@type": "http://www.w3.org/2001/XMLSchema#gYear",
      "@id": "http://purl.org/dc/terms/issued"
    }
```

But when [we get values](https://github.com/periodo/periodo-client/blob/3453f266d101f3909f5ef7010bdff3ff0cc5e387/modules/periodo-app/src/linked-data/utils/make_source_repr.js#L11-L14) for `yearPublished` from Crossref or OCLC, we use their values for the predicated `dc:date` and `schema:datePublished`. Usually these values are just years, but occasionally they are not (for example http://n2t.net/ark:/99152/p0323gx), resulting in invalid triples.

So, we need to either change our context so that the value type is less narrow (`xsd:date` rather than `xsd:gYear`) and rename the key accordingly, or we need to strip out months and days from our external sources.

Which do you prefer, @ptgolden?

**Comment by ptgolden** [comment]
`xsd:date` seems good to me

**Comment by rybesh** [comment]
`xsd:date` is too strict as it would make all the bare year values invalid. Changing to `xsd:string` since we can't predict what Crossref or OCLC will give us.

Fix at https://github.com/periodo/periodo-validation/blob/master/fix/date-published.js but waiting until I submit the patch to close this.
