### ISSUE TITLE
periodCollection -> authority (naming)

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-data#47]

**Comment by ptgolden** [comment]
I assume this won't be retroactively applied to past versions of the dataset (& patches). That means that we will need to write code that deals with both `periodCollection`/`periodCollections` and `authority`/`authorities`

**Comment by rybesh** [comment]
Is that an argument against doing it, or are you just making an observation?

Also isn't the same true of all the data model changes that aren't strictly additive?

**Comment by ptgolden** [comment]
It was an observation. To this point, as far as I can recall, we've only made changes that are additive (in terms of the data model). Checking for `periodCollection` vs `authority` would be a good marker for needing to do that sort of conversion.

It's not a big deal with operating on the dataset as a whole-- it'll just get tricky for visualizing diffs whose endpoints cross that threshold. (Not just for this change, but for all of them that we're doing).

**Comment by rybesh** [comment]
Done in staging by https://github.com/periodo/periodo-validation/blob/master/fix/renaming.js
