### ISSUE TITLE
Originals of deleted duplicate LCSH periods need editing

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-data#50]
We tried very hard to avoid these, but they crept in anyway, so Ryan will need to delete them. Here's the list:

Delete http://n2t.net/ark:/99152/p06c6g3h3wh (duplicate of http://n2t.net/ark:/99152/p06c6g3gfns)

Delete http://n2t.net/ark:/99152/p06c6g35pg5 (duplicate of http://n2t.net/ark:/99152/p06c6g3nnbs, incorrect statement about separate URI for Three Crowns' War -- the links are identical)

Delete http://n2t.net/ark:/99152/p06c6g3z9k9 (duplicate of http://n2t.net/ark:/99152/p06c6g3h)

Delete whichever is more recent of http://n2t.net/ark:/99152/p06c6g3h and http://n2t.net/ark:/99152/p06c6g35vgf

Delete http://n2t.net/ark:/99152/p06c6g3nkxb (duplicate of http://n2t.net/ark:/99152/p06c6g3f3dw)

Delete http://n2t.net/ark:/99152/p06c6g3z9b7 (duplicate of http://n2t.net/ark:/99152/p06c6g3bt2q, though after deletion add alternate Japanese label to the latter)

Delete http://n2t.net/ark:/99152/p06c6g3b46q (duplicate of http://n2t.net/ark:/99152/p06c6g3h2j9, though after deletion add alternate label to the latter)

Delete http://n2t.net/ark:/99152/p06c6g35rqq (duplicate of http://n2t.net/ark:/99152/p06c6g3rhfb, though latter needs to be updated to reflect revision of LCSH entry in 2017 which apparently removed some of earlier variants)

Delete http://n2t.net/ark:/99152/p06c6g3vkbm (duplicate of http://n2t.net/ark:/99152/p06c6g3szt6, though after deletion add alternate label to the latter)

Delete http://n2t.net/ark:/99152/p06c6g3g4sn (duplicate of http://n2t.net/ark:/99152/p06c6g34vjs)

**Comment by rybesh** [comment]
> Delete whichever is more recent of http://n2t.net/ark:/99152/p06c6g3h and http://n2t.net/ark:/99152/p06c6g35vgf

The first URL doesn't resolve; pasting error?

**Comment by atomrab** [comment]
Yup, it's http://n2t.net/ark:/99152/p06c6g3hkgk

**Comment by rybesh** [comment]
Also, just to clarify: after I delete the duplicates, will you be manually making the other changes (e.g. adding alternate labels to the original)?

**Comment by atomrab** [comment]
Yup, I'll take care of it.

**Comment by rybesh** [comment]
Fixed by https://test.perio.do/patches/145/ (see also https://github.com/periodo/periodo-validation/commit/ae4172567c029c79092d3f11bbc62ee7f7eebadb).

I'll leave this open until the other changes mentioned above are done.
