### ISSUE TITLE
Missing spatial coverage values from DBpedia (batch correct)

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-data#51]
Some of our records are missing a spatial coverage value because the lookup list never included them (don't exist in DBpedia, or import failed?). We should add a country value to these before we move over to the bounding-box system, especially since we're going to pull in old values by mapping the DBpedia URIs (right?). They include:

Norway
Cambodia
South Korea (though they have North Korea, for some reason)
Moldova

If these don't exist in DBpedia at all, we should note periods with these spatial coverages and map them to the new set of geometries directly.

**Comment by rybesh** [comment]
These are all in our countries gazetteer now: https://github.com/periodo/periodo-places/blob/master/gazetteers/countries.json
