### ISSUE TITLE
Question about spatial coverage at transitional moment

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-data#53]
@rybesh, there are a number of LCSH headings that currently have sub-country spatial coverage descriptions and no spatial coverage. I was planning to go in and associate those with the larger countries, but it occurs to me that perhaps it would be better to wait and use these as test-cases for the bounding-box selection process?

Conversely, I have a number of LCSH "Byzantine Empire" coverage descriptions that correspond to very different imperial extents. Some have no spatial coverage, others have a standard but incomplete set of countries. I was planning to delete the spatial coverage values from the definitions that do have countries, in anticipation of an eventual bounding-box approach that could be calibrated to the extent of the empire in a given period -- or even pointed to a URI for an entity + shapefile for the Byzantine Empire in, say, 1100. Should I go ahead and strip the countries from the ones that have them, add countries to the ones that don't, or just sit back and wait for a new bounding-box alternative that will pull in the boundaries of the current countries?

**Comment by rybesh** [comment]
We're at the point now where we can start going back and setting more specific spatial coverage values for these, using Wikidata places.
