### ISSUE TITLE
Marine isotope stages (MIS)

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-data#63]
These should have some representation in PeriodO.

https://en.wikipedia.org/wiki/Marine_isotope_stage

**Comment by atomrab** [comment]
Agreed. We should work on the chronostratigraphic periods, too, now probably for a newer version than 2017. Do we need to pick up the thread with Cox et al. for this?

https://data.csiro.au/collections/#collection/CIcsiro:41550 (CC-By)
