### ISSUE TITLE
Character problem with Latin rendering of Russian diacritics from LCHS

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-data#66]
Problem with preferred label of http://n2t.net/ark:/99152/p06c6g3jdnz.

**Comment by ptgolden** [comment]
What's the problem?

**Comment by atomrab** [comment]
My Chrome browser on a Mac is rendering the diacritics as the "unrecognizable" box. Same with http://n2t.net/ark:/99152/p06c6g3892d: 

![image](https://user-images.githubusercontent.com/4740995/87239406-67317900-c3d4-11ea-9ff6-54a330568de8.png)

**Comment by ptgolden** [comment]
Here is what I see:

![image](https://user-images.githubusercontent.com/376031/87336942-a4028a80-c510-11ea-95be-ff968c75212c.png)

Maybe your computer doesn't have the proper fonts to render [ALA-LC](https://en.wikipedia.org/wiki/ALA-LC_romanization_for_Russian) transliteration characters?

**Comment by ptgolden** [comment]
Do you see the same "unrecognizable" boxes here? <http://id.loc.gov/authorities/subjects/sh96000483.html>

**Comment by rybesh** [comment]
Here's what they look like in macos Safari:

<img width="416" alt="Screen Shot 2020-07-13 at 2 03 57 PM" src="https://user-images.githubusercontent.com/84592/87337741-e8425a80-c511-11ea-9832-b99e993ba245.png">
<img width="179" alt="Screen Shot 2020-07-13 at 2 03 44 PM" src="https://user-images.githubusercontent.com/84592/87337745-ea0c1e00-c511-11ea-8cff-67bce88b0eed.png">

And macos Chrome:

<img width="402" alt="Screen Shot 2020-07-13 at 2 06 15 PM" src="https://user-images.githubusercontent.com/84592/87337844-20499d80-c512-11ea-892a-cf6fda00ab62.png">
<img width="175" alt="Screen Shot 2020-07-13 at 2 06 39 PM" src="https://user-images.githubusercontent.com/84592/87337848-22136100-c512-11ea-8a24-764163e8f99a.png">

The LOC link above looks the same (correct) in both Safari and Chrome.

**Comment by rybesh** [comment]
If I change the font in the PeriodO client to `'Open Sans', Arial, Helvetica, sans-serif` it looks OK.

**Comment by rybesh** [comment]
Currently is it just `sans-serif`.

**Comment by ptgolden** [comment]
What is Open Sans and why would be the first option? (I would be fine with it, just checking)

**Comment by ptgolden** [comment]
Ah, that's what LOC uses

**Comment by ptgolden** [comment]
What happens if you change it to "Arial, Helvetica, sans-serif"?

**Comment by rybesh** [comment]
Still works. Helvetica doesn't work, but Arial works on Chrome and Safari, and Open Sans works on Chrome. (Open Sans comes with Chrome, I think.) 

From what I can tell Arial is the only font that is widely installed and supports all (?) of Unicode, but I don't know what the deal is on Linux.

**Comment by rybesh** [comment]
Too bad, because Arial is ugly.

**Comment by rybesh** [comment]
If we wanted to go the web fonts route, there is this: https://www.google.com/get/noto/

**Comment by ptgolden** [comment]
I used [Source Sans](https://fonts.adobe.com/fonts/source-sans) for DrEdGE, and was pretty happy with it. I'm always happy not to do Google things.

**Comment by ptgolden** [comment]
But it doesn't have support for the glyphs we want ([test](https://fonts.google.com/specimen/Source+Sans+Pro?preview.text=Chechni%EF%B8%A0a%EF%B8%A1+(Russia)--History--Civil+War,+1994-&preview.text_type=custom#standard-styles))
![image](https://user-images.githubusercontent.com/376031/87373109-0c745a80-c557-11ea-8a0e-ac672166590f.png)

I don't know what to do about this, but it's not an issue with the data. My impression is that it's an issue with font rendering in browsers. I imagine it's some combination between how browsers handle fallback fonts and also how they handle modifier characters, like the weird arcs that LOC uses for rendering Russian in English.

I would be fine using that font you linked. It, with bold and italic versions, would be 1.5mb. But I'm sure easily cacheable.

**Comment by rybesh** [comment]
You're right that its not an issue with the data; there's just very few fonts that completely cover the broad range of languages we have. Why don't we just use Arial for now and look into using a webfont if we hate it?

I don't like using Google stuff either, but they're free/open-source, and we could host the font ourselves. That's what I do on aeshin.org: https://aeshin.org/static/type/CharisSILR-webfont.woff

**Comment by rybesh** [comment]
Fixed by https://github.com/periodo/periodo-client/commit/aba87311d5ae59c9ea857d46ee77d7297f069faf
